### PR TITLE
Update settings.xml

### PR DESCRIPTION
**Pull request by nickidw**
Corrected naming for Routing

### CODE REVIEW

**Comment by kittoku** [comment]
Thank you, @nickidw ! Do you accept [CONTRIBUTING.md](https://github.com/kittoku/Open-SSTP-Client/blob/main/CONTRIBUTING.md)? 

It would be great if you could fix [other six "routeing"s](https://github.com/search?q=repo%3Akittoku%2FOpen-SSTP-Client%20routeing&type=code) when you have time.

**Comment by nickidw** [comment]
No problem, let me look for them!

**Comment by nickidw** [comment]
All updated.

**Comment by kittoku** [comment]
Awesome! Thank you again!

**Comment by nickidw** [comment]
My pleasure, thanks for the great software.

**Pull request merged**
